### ISSUE TITLE
bug running scss in default min() function

### ISSUE THREAD

**Issue by karkbt** [scssphp/scssphp#444]
When compiling the bootstrap sass it gives an error in several min() of the css, how do I solve this

```
<html>
<body>
<!--StartFragment-->



<b>Fatal error</b>:  Uncaught Leafo\ScssPhp\Exception\CompilerException: function is not a number: C:\xampp\htdocs\bring/wp-content/themes/bring/assets/sass/base/03-generic/breakpoints.scss on line 96, at column 3
  | Call Stack:
  | #0 mixin media C:\xampp\htdocs\bring/wp-content/themes/bring/assets/sass/base/03-generic/breakpoints.scss on line 101 in C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php:4184
  | Stack trace:
  | #0 C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php(5512): Leafo\ScssPhp\Compiler-&gt;throwError('function is not...', 'function')
  | #1 C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php(5471): Leafo\ScssPhp\Compiler-&gt;getNormalizedNumbers(Array)
  | #2 [internal function]: Leafo\ScssPhp\Compiler-&gt;libMin(Array, Array)
  | #3 C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php(4328): call_user_func(Array, Array, Array)
  | #4 C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php(2755): Leafo\ScssPhp\Compiler-&gt;callNativeFunct in <b>C:\xampp\htdocs\bring\wp-content\themes\bring\inc\scssphp\src\Compiler.php</b> on line <b>4184</b><br />
 

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by stof** [comment]
when compiling which version of bootstrap exactly ?
Also, looking at the path in the stack trace, I even doubt this is Bootstrap.

**Comment by stof** [comment]
Actually, I will close this. The error message mentions `Leafo\ScssPhp` as namespace. This means you are not using this project at all, but the older https://github.com/leafo/scssphp
