### ISSUE TITLE
Call to undefined method ScssPhp\ScssPhp\Compiler::compileString()

### ISSUE THREAD

**Issue by sebrose** [scssphp/scssphp#740]
I'm working with OpenCart 3.0.4.0 and PHP 8.0, which are supposed to be compatible. I cleared the SASS cache and this is the error that I got:

```
Call to undefined method ScssPhp\ScssPhp\Compiler::compileString() in /Users/seb/Projects/shop/admin/controller/startup/sass.php:17 
Stack trace: 
#0 /Users/seb/Projects/shop/system/storageundh3m8jmtxd/modification/system/engine/action.php(79): ControllerStartupSass->index() 
#1 /Users/seb/Projects/shop/system/engine/router.php(67): Action->execute(Object(Registry)) 
#2 /Users/seb/Projects/shop/system/engine/router.php(46): Router->execute(Object(Action)) 
#3 /Users/seb/Projects/shop/system/framework.php(179): Router->dispatch(Object(Action), Object(Action)) 
#4 /Users/seb/Projects/shop/system/startup.php(104): require_once('/Users/seb/Proj...') 
#5 /Users/seb/Projects/shop/admin/index.php(19): start('admin') 
#6 {main} thrown in /Users/seb/Projects/shop/admin/controller/startup/sass.php on line 17
```

Can anyone point me towards a fix - or a clue as to what might be happening?

Thanks.

**Comment by stof** [comment]
closing as there was no answer
